### ISSUE TITLE
Feature: Config File

### ISSUE THREAD

**Issue by Ivelok** [leominov/network-access-exporter#2]
Можно ли сделать хранение конфигурации запуска в файле? 

Также было бы круто сделать группирование хостов. Пример:
```
database:
  postgres:
    postgresql-db-01:5432:
    postgresql-db-02:5432:
  oracle:
    oracle-db-01:1521:
foobar-resource:
  test:
    foobar-test:443:
    foobar-kibana:80:
  prod:
    foobar-prod:443:
```

**Comment by leominov** [comment]
Проверь версия 0.5.0

**Comment by leominov** [comment]
Можно задавать так:

```
resources:
  atlassian:
    - jira.yandex.ru:443
  devops:
    - grafana.com:443
  database#postgres:
    - yandex.ru:443
    - google.com:443
```

можно так:

```
resources:
  - jira.yandex.ru:443
  - grafana.com:443
  - yandex.ru:443
  - google.com:443
```
